version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.13.2-browsers

    steps:
      - checkout
      - run: npm install
      - run: npm run linter

  test:
    docker:
      - image: cimg/node:16.13.2-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run unit-tests
      - run: npm run ui-tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

