version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:18.14.2

    steps:
      - checkout
      - run: npm install
      - run: npm run linter

  test:
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run: google-chrome --version
      - run: npm install
      - run: npm run unit-tests
      - run: npm run ui-tests -- --headless --no-sandbox

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
