# this is the name of our action.
# this will be displayed in 'Actions' tab on your repo's github page when running.
name: deploy staging

# the trigger for the action.
# we are interested only in pushes onto a 'dev' branch
on:
  push:
    branches:
      - main

# jobs to be done.
# each job has multiple steps.
# jobs can depend on other jobs, but in out case it's very linear.
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    # steps are what you see in logs in Actions
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./ohana-homes/package-lock.json
      - run: |
          cd ./ohana-homes
          npm install
          npm run build
      - name: copy the files
        uses: appleboy/scp-action@master
        with:
          host:  ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "ohana-homes/build/*"
          target: "/var/www/kman.space/test-github-actions"
          tar_tmp_path: "/home/github-action-deploy/tmp"
          overwrite: true
          # we can strip to 2 to get rid of build folder in output
          strip_components: 1
