name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present
      - run: |
          npm run pa11y-ci src/assets/snapshots/HomePage-snapshot.html
          npm run pa11y-ci src/assets/snapshots/AboutUsPage-snapshot.html
          npm run pa11y-ci src/assets/snapshots/HeroPage-snapshot.html
          npm run pa11y-ci src/assets/snapshots/ContactUsPage-snapshot.html